import type { Influencer } from "@/components/influencer-dashboard";

export const mockInfluencers: Influencer[] = [
  {
    id: "inf1",
    name: "Alex Johnson",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram", "YouTube"],
    score: 92,
    dateAdded: "2023-05-15T10:30:00Z",
  },
  {
    id: "inf2",
    name: "Samantha Lee",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram"],
    score: 88,
    dateAdded: "2023-06-22T14:45:00Z",
  },
  {
    id: "inf3",
    name: "Marcus Chen",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["YouTube"],
    score: 76,
    dateAdded: "2023-07-10T09:15:00Z",
  },
  {
    id: "inf4",
    name: "Priya Patel",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram", "YouTube"],
    score: 95,
    dateAdded: "2023-04-05T11:20:00Z",
  },
  {
    id: "inf5",
    name: "Jordan Smith",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["Instagram"],
    score: 72,
    dateAdded: "2023-08-18T16:30:00Z",
  },
  {
    id: "inf6",
    name: "Emma Wilson",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["YouTube"],
    score: 68,
    dateAdded: "2023-09-02T13:45:00Z",
  },
  {
    id: "inf7",
    name: "David Kim",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram", "YouTube"],
    score: 91,
    dateAdded: "2023-03-28T10:00:00Z",
  },
  {
    id: "inf8",
    name: "Olivia Garcia",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["Instagram"],
    score: 79,
    dateAdded: "2023-07-25T15:15:00Z",
  },
  {
    id: "inf9",
    name: "Michael Brown",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["YouTube"],
    score: 86,
    dateAdded: "2023-05-30T12:10:00Z",
  },
  {
    id: "inf10",
    name: "Sophia Martinez",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["Instagram", "YouTube"],
    score: 74,
    dateAdded: "2023-08-05T09:30:00Z",
  },
  {
    id: "inf11",
    name: "Ethan Taylor",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["Instagram"],
    score: 65,
    dateAdded: "2023-09-15T14:20:00Z",
  },
  {
    id: "inf12",
    name: "Ava Williams",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram", "YouTube"],
    score: 93,
    dateAdded: "2023-04-18T11:45:00Z",
  },
  {
    id: "inf13",
    name: "Noah Anderson",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["YouTube"],
    score: 71,
    dateAdded: "2023-06-10T16:00:00Z",
  },
  {
    id: "inf14",
    name: "Isabella Thomas",
    profilePicture: "/placeholder-user.jpg",
    tier: "Gold",
    platforms: ["Instagram"],
    score: 89,
    dateAdded: "2023-05-05T10:15:00Z",
  },
  {
    id: "inf15",
    name: "Liam Jackson",
    profilePicture: "/placeholder-user.jpg",
    tier: "Silver",
    platforms: ["Instagram", "YouTube"],
    score: 77,
    dateAdded: "2023-07-20T13:30:00Z",
  },
];
